export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    darkText: false,
    topLine: 'Premium Bank',
    headline: 'Voluptate reprehenderit reprehenderit elit ex elit aliquip ipsum laboris minim.',
    description: 'Exercitation dolor magna culpa eu est officia nulla irure. Labore anim veniam id nostrud veniam magna enim excepteur sunt minim tempor non do ex. Irure commodo sunt deserunt elit velit commodo voluptate. Sint consequat aute consequat occaecat dolore magna eiusmod tempor excepteur non ut.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    darkcolorbtn: true,
    primary: true,
};

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    darkText: true,
    topLine: 'Premium Bank 2',
    headline: 'Voluptate reprehenderit reprehenderit elit ex elit aliquip ipsum laboris minim.',
    description: 'Exercitation dolor magna culpa eu est officia nulla irure. Labore anim veniam id nostrud veniam magna enim excepteur sunt minim tempor non do ex. Irure commodo sunt deserunt elit velit commodo voluptate. Sint consequat aute consequat occaecat dolore magna eiusmod tempor excepteur non ut.',
    buttonLabel: 'Get started 2',
    imgStart: true,
    img: require('../../images/svg-2.svg').default,
    alt: 'Car 2',
    darkcolorbtn: false,
    primary: false,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    darkText: true,
    topLine: 'Start now',
    headline: 'Voluptate reprehenderit reprehenderit elit ex elit aliquip ipsum laboris minim.',
    description: 'Exercitation dolor magna culpa eu est officia nulla irure. Labore anim veniam id nostrud veniam magna enim excepteur sunt minim tempor non do ex. Irure commodo sunt deserunt elit velit commodo voluptate. Sint consequat aute consequat occaecat dolore magna eiusmod tempor excepteur non ut.',
    buttonLabel: 'Get started 3',
    imgStart: false,
    img: require('../../images/svg-3.svg').default,
    alt: 'paper',
    darkcolorbtn: false,
    primary: false,
}
